export type SnowflakeObjectType = AccountObjectType | SchemaObjectType

export enum AccountObjectType {
  USER = 'USER',
  RESOURCE_MONITOR = 'RESOURCE MONITOR',
  WAREHOUSE = 'WAREHOUSE',
  DATABASE = 'DATABASE',
  SCHEMA = 'SCHEMA',
  INTEGRATION = 'INTEGRATION',
  FAILOVER_GROUP = 'FAILOVER GROUP',
  REPLICATION_GROUP = 'REPLICATION GROUP'
}

export enum SchemaObjectType {
  ALERT = 'ALERT',
  DYNAMIC_TABLE = 'DYNAMIC TABLE',
  EVENT_TABLE = 'EVENT TABLE',
  FILE_FORMAT = 'FILE FORMAT',
  FUNCTION = 'FUNCTION',
  PROCEDURE = 'PROCEDURE',
  SECRET = 'SECRET',
  SEQUENCE = 'SEQUENCE',
  PIPE = 'PIPE',
  MASKING_POLICY = 'MASKING POLICY',
  PASSWORD_POLICY = 'PASSWORD POLICY',
  ROW_ACCESS_POLICY = 'ROW ACCESS POLICY',
  SESSION_POLICY = 'SESSION POLICY',
  TAG = 'TAG',
  STAGE = 'STAGE',
  STREAM = 'STREAM',
  TABLE = 'TABLE',
  EXTERNAL_TABLE = 'EXTERNAL TABLE',
  TASK = 'TASK',
  VIEW = 'VIEW',
  MATERIALIZED_VIEW = 'MATERIALIZED VIEW'
}

export enum SchemaObjectTypePlural {
  ALERTS = 'ALERTS',
  DYNAMIC_TABLES = 'DYNAMIC TABLES',
  EVENT_TABLES = 'EVENT TABLES',
  FILE_FORMATS = 'FILE FORMATS',
  FUNCTIONS = 'FUNCTIONS',
  PROCEDURES = 'PROCEDURES',
  SECRETS = 'SECRETS',
  SEQUENCES = 'SEQUENCES',
  PIPES = 'PIPES',
  MASKING_POLICIES = 'MASKING POLICIES',
  PASSWORD_POLICIES = 'PASSWORD POLICIES',
  ROW_ACCESS_POLICIES = 'ROW ACCESS POLICIES',
  SESSION_POLICIES = 'SESSION POLICIES',
  TAGS = 'TAGS',
  STAGES = 'STAGES',
  STREAMS = 'STREAMS',
  TABLES = 'TABLES',
  EXTERNAL_TABLES = 'EXTERNAL TABLES',
  TASKS = 'TASKS',
  VIEWS = 'VIEWS',
  MATERIALIZED_VIEWS = 'MATERIALIZED VIEWS'
}

export function pluralize(objectType: SchemaObjectType): SchemaObjectTypePlural {
  let plural = ''
  if(objectType.includes('POLICY')) {
    plural = objectType.replace('POLICY', 'POLICIES')
  } else {
    plural = objectType + 'S'
  }
  plural = plural.replace(/\s/gi, '_')

  return SchemaObjectTypePlural[plural as keyof typeof SchemaObjectTypePlural]
}