-- Create COMMON owner access role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_COMMON_FULL_AR";
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT ROLE "PROD_DB_COMMON_FULL_AR" TO ROLE "SYSADMIN";

-- Create RAW owner access role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_RAW_FULL_AR";
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT ROLE "PROD_DB_RAW_FULL_AR" TO ROLE "SYSADMIN";

-- Create PROD_BI owner access role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_BI_FULL_AR";
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON WAREHOUSE "PROD_BI" TO ROLE "PROD_BI_FULL_AR";
GRANT ROLE "PROD_BI_FULL_AR" TO ROLE "SYSADMIN";

-- Create PROD_DSCI owner access role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DSCI_FULL_AR";
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON WAREHOUSE "PROD_DSCI" TO ROLE "PROD_DSCI_FULL_AR";
GRANT ROLE "PROD_DSCI_FULL_AR" TO ROLE "SYSADMIN";

-- Create PROD_ELT owner access role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_ELT_FULL_AR";
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON WAREHOUSE "PROD_ELT" TO ROLE "PROD_ELT_FULL_AR";
GRANT ROLE "PROD_ELT_FULL_AR" TO ROLE "SYSADMIN";

-- Create and Grant Privileges to Access Role PROD_DB_COMMON_R_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_COMMON_R_AR";
GRANT ROLE "PROD_DB_COMMON_R_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_R_AR";

-- Create and Grant Privileges to Access Role PROD_DB_COMMON_RW_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_COMMON_RW_AR";
GRANT ROLE "PROD_DB_COMMON_RW_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT INSERT ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT UPDATE ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT DELETE ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT REFERENCES ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT INSERT ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT UPDATE ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT DELETE ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT WRITE ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT WRITE ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT MONITOR ON ALL TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT OPERATE ON ALL TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT MONITOR ON FUTURE TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";
GRANT OPERATE ON FUTURE TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_RW_AR";

-- Create and Grant Privileges to Access Role PROD_DB_COMMON_FULL_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_COMMON_FULL_AR";
GRANT ROLE "PROD_DB_COMMON_FULL_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT INSERT ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT UPDATE ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT DELETE ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT REFERENCES ON ALL TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT INSERT ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT UPDATE ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT DELETE ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT WRITE ON FUTURE STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT WRITE ON ALL STAGES IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT MONITOR ON ALL TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OPERATE ON ALL TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT MONITOR ON FUTURE TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";
GRANT OPERATE ON FUTURE TASKS IN SCHEMA "PROD_DB"."COMMON" TO ROLE "PROD_DB_COMMON_FULL_AR";

-- Create and Grant Privileges to Access Role PROD_DB_RAW_R_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_RAW_R_AR";
GRANT ROLE "PROD_DB_RAW_R_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_R_AR";

-- Create and Grant Privileges to Access Role PROD_DB_RAW_RW_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_RAW_RW_AR";
GRANT ROLE "PROD_DB_RAW_RW_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT INSERT ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT UPDATE ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT DELETE ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT REFERENCES ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT INSERT ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT UPDATE ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT DELETE ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT WRITE ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT WRITE ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT MONITOR ON ALL TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT OPERATE ON ALL TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT MONITOR ON FUTURE TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";
GRANT OPERATE ON FUTURE TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_RW_AR";

-- Create and Grant Privileges to Access Role PROD_DB_RAW_FULL_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DB_RAW_FULL_AR";
GRANT ROLE "PROD_DB_RAW_FULL_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR" REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT READ ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT INSERT ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT UPDATE ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT DELETE ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT REFERENCES ON ALL TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT INSERT ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT UPDATE ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT DELETE ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT WRITE ON FUTURE STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT WRITE ON ALL STAGES IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT MONITOR ON ALL TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OPERATE ON ALL TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT MONITOR ON FUTURE TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";
GRANT OPERATE ON FUTURE TASKS IN SCHEMA "PROD_DB"."RAW" TO ROLE "PROD_DB_RAW_FULL_AR";

-- Create and Grant Privileges to Access Role SOG_SOME_OBJECTS_R_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "SOG_SOME_OBJECTS_R_AR";
GRANT ROLE "SOG_SOME_OBJECTS_R_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT SELECT ON TABLE "PROD_DB"."RAW"."MY_TABLE" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT SELECT ON TABLE "PROD_DB"."COMMON"."SEED_DATA" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT SELECT ON VIEW "PROD_DB"."RAW"."MY_VIEW" TO ROLE "SOG_SOME_OBJECTS_R_AR";
GRANT SELECT ON VIEW "PROD_DB"."COMMON"."ANOTHER_VIEW" TO ROLE "SOG_SOME_OBJECTS_R_AR";

-- Create and Grant Privileges to Access Role SOG_SOME_OBJECTS_RW_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "SOG_SOME_OBJECTS_RW_AR";
GRANT ROLE "SOG_SOME_OBJECTS_RW_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE "PROD_DB" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."RAW" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT USAGE ON SCHEMA "PROD_DB"."COMMON" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT SELECT ON TABLE "PROD_DB"."RAW"."MY_TABLE" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT SELECT ON TABLE "PROD_DB"."COMMON"."SEED_DATA" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT SELECT ON VIEW "PROD_DB"."RAW"."MY_VIEW" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT SELECT ON VIEW "PROD_DB"."COMMON"."ANOTHER_VIEW" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT INSERT ON TABLE "PROD_DB"."RAW"."MY_TABLE" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT UPDATE ON TABLE "PROD_DB"."RAW"."MY_TABLE" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT DELETE ON TABLE "PROD_DB"."RAW"."MY_TABLE" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT INSERT ON TABLE "PROD_DB"."COMMON"."SEED_DATA" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT UPDATE ON TABLE "PROD_DB"."COMMON"."SEED_DATA" TO ROLE "SOG_SOME_OBJECTS_RW_AR";
GRANT DELETE ON TABLE "PROD_DB"."COMMON"."SEED_DATA" TO ROLE "SOG_SOME_OBJECTS_RW_AR";

-- Create and Grant Privileges to Access Role PROD_BI_U_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_BI_U_AR";
GRANT ROLE "PROD_BI_U_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_BI" TO ROLE "PROD_BI_U_AR";

-- Create and Grant Privileges to Access Role PROD_BI_UM_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_BI_UM_AR";
GRANT ROLE "PROD_BI_UM_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_BI" TO ROLE "PROD_BI_UM_AR";
GRANT MONITOR ON WAREHOUSE "PROD_BI" TO ROLE "PROD_BI_UM_AR";

-- Create and Grant Privileges to Access Role PROD_DSCI_U_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DSCI_U_AR";
GRANT ROLE "PROD_DSCI_U_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_DSCI" TO ROLE "PROD_DSCI_U_AR";

-- Create and Grant Privileges to Access Role PROD_DSCI_UM_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_DSCI_UM_AR";
GRANT ROLE "PROD_DSCI_UM_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_DSCI" TO ROLE "PROD_DSCI_UM_AR";
GRANT MONITOR ON WAREHOUSE "PROD_DSCI" TO ROLE "PROD_DSCI_UM_AR";

-- Create and Grant Privileges to Access Role PROD_ELT_U_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_ELT_U_AR";
GRANT ROLE "PROD_ELT_U_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_ELT" TO ROLE "PROD_ELT_U_AR";

-- Create and Grant Privileges to Access Role PROD_ELT_UM_AR
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_ELT_UM_AR";
GRANT ROLE "PROD_ELT_UM_AR" TO ROLE "SYSADMIN";
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE "PROD_ELT" TO ROLE "PROD_ELT_UM_AR";
GRANT MONITOR ON WAREHOUSE "PROD_ELT" TO ROLE "PROD_ELT_UM_AR";

-- Grant Access Roles to Functional Roles
USE ROLE SECURITYADMIN;
GRANT ROLE "PROD_DB_COMMON_R_AR" TO ROLE "DATA_ANALYST";
GRANT ROLE "PROD_DB_RAW_R_AR" TO ROLE "DATA_ANALYST";
GRANT ROLE "SOG_SOME_OBJECTS_R_AR" TO ROLE "DATA_ANALYST";
GRANT ROLE "PROD_BI_U_AR" TO ROLE "DATA_ANALYST";
GRANT ROLE "PROD_DB_COMMON_RW_AR" TO ROLE "DATA_SCIENTIST";
GRANT ROLE "PROD_DB_RAW_R_AR" TO ROLE "DATA_SCIENTIST";
GRANT ROLE "PROD_DSCI_U_AR" TO ROLE "DATA_SCIENTIST";
GRANT ROLE "PROD_DB_COMMON_FULL_AR" TO ROLE "ELT_TOOL";
GRANT ROLE "PROD_DB_RAW_FULL_AR" TO ROLE "ELT_TOOL";
GRANT ROLE "SOG_SOME_OBJECTS_RW_AR" TO ROLE "ELT_TOOL";
GRANT ROLE "PROD_ELT_U_AR" TO ROLE "ELT_TOOL";