--
-- PROD Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_COMMON_R_AR";
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_COMMON_RW_AR";
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "PROD_EXAMPLE_DB"."COMMON" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_RAW_R_AR";
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "PROD_EXAMPLE_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "PROD_EXAMPLE_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "PROD_EXAMPLE_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "PROD_SANDBOX_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "PROD_BI_WH_U_AR";
DROP ROLE "PROD_BI_WH_UM_AR";
DROP ROLE "PROD_BI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "PROD_BI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "PROD_DSCI_WH_U_AR";
DROP ROLE "PROD_DSCI_WH_UM_AR";
DROP ROLE "PROD_DSCI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "PROD_DSCI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "PROD_ELT_WH_U_AR";
DROP ROLE "PROD_ELT_WH_UM_AR";
DROP ROLE "PROD_ELT_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "PROD_ELT_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "PROD_DEVOPS_WH_U_AR";
DROP ROLE "PROD_DEVOPS_WH_UM_AR";
DROP ROLE "PROD_DEVOPS_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "PROD_DEVOPS_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

--
-- DEV Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_COMMON_R_AR";
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_COMMON_RW_AR";
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "DEV_EXAMPLE_DB"."COMMON" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_RAW_R_AR";
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "DEV_EXAMPLE_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "DEV_EXAMPLE_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "DEV_EXAMPLE_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "DEV_SANDBOX_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "DEV_BI_WH_U_AR";
DROP ROLE "DEV_BI_WH_UM_AR";
DROP ROLE "DEV_BI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "DEV_BI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "DEV_DSCI_WH_U_AR";
DROP ROLE "DEV_DSCI_WH_UM_AR";
DROP ROLE "DEV_DSCI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "DEV_DSCI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "DEV_ELT_WH_U_AR";
DROP ROLE "DEV_ELT_WH_UM_AR";
DROP ROLE "DEV_ELT_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "DEV_ELT_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "DEV_DEVOPS_WH_U_AR";
DROP ROLE "DEV_DEVOPS_WH_UM_AR";
DROP ROLE "DEV_DEVOPS_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "DEV_DEVOPS_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

--
-- TEST Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_COMMON_R_AR";
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_COMMON_RW_AR";
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "TEST_EXAMPLE_DB"."COMMON" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_RAW_R_AR";
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "TEST_EXAMPLE_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "TEST_EXAMPLE_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "TEST_EXAMPLE_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "TEST_SANDBOX_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "TEST_BI_WH_U_AR";
DROP ROLE "TEST_BI_WH_UM_AR";
DROP ROLE "TEST_BI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "TEST_BI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "TEST_DSCI_WH_U_AR";
DROP ROLE "TEST_DSCI_WH_UM_AR";
DROP ROLE "TEST_DSCI_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "TEST_DSCI_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "TEST_ELT_WH_U_AR";
DROP ROLE "TEST_ELT_WH_UM_AR";
DROP ROLE "TEST_ELT_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "TEST_ELT_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "TEST_DEVOPS_WH_U_AR";
DROP ROLE "TEST_DEVOPS_WH_UM_AR";
DROP ROLE "TEST_DEVOPS_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "TEST_DEVOPS_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;