--
-- PROD Environment
--

USE ROLE SYSADMIN;
DROP DATABASE "PROD_EXAMPLE_DB";
DROP DATABASE "PROD_SANDBOX_DB";

--
-- DEV Environment
--

USE ROLE SYSADMIN;
DROP DATABASE "DEV_EXAMPLE_DB";
DROP DATABASE "DEV_SANDBOX_DB";

--
-- TEST Environment
--

USE ROLE SYSADMIN;
DROP DATABASE "TEST_EXAMPLE_DB";
DROP DATABASE "TEST_SANDBOX_DB";