--
-- PROD Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "PROD_DATA_ANALYST_ROLE";
DROP ROLE IF EXISTS "PROD_DATA_SCIENTIST_ROLE";
DROP ROLE IF EXISTS "PROD_ELT_TOOL_ROLE";
DROP ROLE IF EXISTS "PROD_DEVOPS_ROLE";

--
-- DEV Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "DEV_DATA_ANALYST_ROLE";
DROP ROLE IF EXISTS "DEV_DATA_SCIENTIST_ROLE";
DROP ROLE IF EXISTS "DEV_ELT_TOOL_ROLE";
DROP ROLE IF EXISTS "DEV_DEVOPS_ROLE";

--
-- TEST Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "TEST_DATA_ANALYST_ROLE";
DROP ROLE IF EXISTS "TEST_DATA_SCIENTIST_ROLE";
DROP ROLE IF EXISTS "TEST_ELT_TOOL_ROLE";
DROP ROLE IF EXISTS "TEST_DEVOPS_ROLE";