--
-- PROD Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "PROD_SYSADMIN";
GRANT ROLE "PROD_SYSADMIN" TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "PROD_SYSADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "PROD_SYSADMIN";

--
-- DEV Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "DEV_SYSADMIN";
GRANT ROLE "DEV_SYSADMIN" TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "DEV_SYSADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "DEV_SYSADMIN";

--
-- TEST Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "TEST_SYSADMIN";
GRANT ROLE "TEST_SYSADMIN" TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "TEST_SYSADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "TEST_SYSADMIN";