USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS "PROD_BI_WH" WITH INITIALLY_SUSPENDED = FALSE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "PROD_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 2
MAX_CLUSTER_COUNT = 10
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 18540
AUTO_RESUME = FALSE
ENABLE_QUERY_ACCELERATION = FALSE
STATEMENT_TIMEOUT_IN_SECONDS = 3600
RESOURCE_MONITOR = FOO_PROD
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "PROD_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "PROD_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "PROD_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS "DEV_BI_WH" WITH INITIALLY_SUSPENDED = FALSE WAREHOUSE_SIZE = SMALL;
ALTER WAREHOUSE "DEV_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = SMALL
MIN_CLUSTER_COUNT = 3
MAX_CLUSTER_COUNT = 9
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 18000
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
STATEMENT_TIMEOUT_IN_SECONDS = 60
RESOURCE_MONITOR = FOO_DEV
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "DEV_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "DEV_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "DEV_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS "TEST_BI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "TEST_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "TEST_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

CREATE WAREHOUSE IF NOT EXISTS "TEST_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;
