--
-- PROD Environment
--

USE ROLE "PROD_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "PROD_BI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "PROD_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 2
MAX_CLUSTER_COUNT = 10
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 18540
AUTO_RESUME = FALSE;

CREATE WAREHOUSE IF NOT EXISTS "PROD_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "PROD_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "PROD_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;


--
-- DEV Environment
--

USE ROLE "DEV_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "DEV_BI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = SMALL;
ALTER WAREHOUSE "DEV_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = SMALL
MIN_CLUSTER_COUNT = 3
MAX_CLUSTER_COUNT = 9
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 18000
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "DEV_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "DEV_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "DEV_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;


--
-- TEST Environment
--

USE ROLE "TEST_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "TEST_BI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_BI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "TEST_DSCI_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_DSCI_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "TEST_ELT_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_ELT_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS "TEST_DEVOPS_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "TEST_DEVOPS_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE;
