export enum Privilege {
  SELECT = 'SELECT',
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  REFERENCES = 'REFERENCES',
  USAGE = 'USAGE',
  READ = 'READ',
  WRITE = 'WRITE',
  MONITOR = 'MONITOR',
  OPERATE = 'OPERATE',
  OWNERSHIP = 'OWNERSHIP',
}
